version: '3'
services:
  mysql-container:
    image: 'mysql:latest'
    ports:
      - '33061:3306'
      - '33062:3306'
      - '33063:3306'
      - '33064:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'ticket-booking-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
  eureka-container:
    depends_on:
      - mysql-container
    restart: always
    build: ./eureka
    ports:
      - '9999:9999'
  authentication:
    depends_on:
      - mysql-container
      - eureka-container
    restart: always
    build: ./authentication
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-container:3306/ticket-booking-db?useSSL=false&allowPublicKeyRetrieval=true'
  gateway:
    depends_on:
      - mysql-container
      - eureka-container
      - authentication
    restart: always
    build: ./gateway
    ports:
      - '8888:8888'
  city:
    depends_on:
      - mysql-container
      - eureka-container
      - authentication
      - gateway
    restart: always
    build: ./city
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-container:3306/ticket-booking-db?useSSL=false&allowPublicKeyRetrieval=true'
  movie:
    depends_on:
      - mysql-container
      - eureka-container
      - authentication
      - gateway
    restart: always
    build: ./movie
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-container:3306/ticket-booking-db?useSSL=false&allowPublicKeyRetrieval=true'
  theatre:
    depends_on:
      - mysql-container
      - eureka-container
      - authentication
      - gateway
    restart: always
    build: ./theatre
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-container:3306/ticket-booking-db?useSSL=false&allowPublicKeyRetrieval=true'
  ticket:
    depends_on:
      - mysql-container
      - eureka-container
      - authentication
      - gateway
    restart: always
    build: ./ticket
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-container:3306/ticket-booking-db?useSSL=false&allowPublicKeyRetrieval=true'